//
// Machine generated by compile-mbh from ./qa_bitset.mbh
//
// protocol-classes: qa-disconnect-cs qa-bitset-cs qa-bitset 
//
#include <mblock/protocol_class.h>
#include <unistd.h>
static const char
protocol_class_init_data[108] = {
  7, 2, 0, 16, 113, 97, 45, 100, 105, 115, 99, 111, 110, 110, 101, 99, 
  116, 45, 99, 115, 7, 7, 2, 0, 3, 97, 99, 107, 6, 7, 7, 2, 
  0, 11, 115, 101, 108, 101, 99, 116, 45, 112, 105, 112, 101, 6, 6, 7, 
  2, 0, 12, 113, 97, 45, 98, 105, 116, 115, 101, 116, 45, 99, 115, 7, 
  6, 7, 7, 2, 0, 10, 115, 101, 110, 100, 45, 98, 97, 116, 99, 104, 
  6, 6, 7, 2, 0, 9, 113, 97, 45, 98, 105, 116, 115, 101, 116, 7, 
  7, 2, 0, 4, 100, 97, 116, 97, 6, 7, 6, 6, 
};
static mb_protocol_class_init _init_(protocol_class_init_data, sizeof(protocol_class_init_data));
